# Generated by Django 3.0 on 2020-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
